### ISSUE TITLE
Braille Character (Points 4, 5, 6) Alignment

### ISSUE THREAD

**Issue by ghost** [notofonts/symbols#48]

**Comment by myfonj** [comment]
Heads up: despite this issue in the font itself is long resolved, the derived Android "NotoSansSymbols-Regular-Subsetted.ttf" system font is apparently still stuck on the wrong old version and (IIUC) hadn't been refreshed since [`year: 2017 month: 3 day: 18`](https://cs.android.com/android/platform/superproject/main/+/main:external/noto-fonts/notosanssymbols/METADATA).

See:
- specific **[Android issue `407473720` _"Braille being rendered incorrectly"_](https://issuetracker.google.com/issues/407473720)** addressing this concrete problem,
- general [Android issue `366415133` _"Noto fonts outdated and missing"_](https://issuetracker.google.com/issues/366415133) addressing overall neglect,
- and [Google Fonts issue `3935` _"Right side only braille cells (dots ⊆ 4568) incorrect in Noto except Symbols 2, on mobile only"_](https://github.com/google/fonts/issues/3935) with meticulous investigations leading here (and to aforementioned Android issues).

So in effect, displaying Braille on Android screen *reliably* **today** still demands loading/embedding a third-party font ☹️.
